apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: notary-volume
provisioner: volume.csi.storage.gke.io
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  tier: standard
  #  should use the network of GKE cluster
  network: vpctest1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: notarypvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: notary-volume
  resources:
    requests:
      storage: 1Ti
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: partya-volume
provisioner: volume.csi.storage.gke.io
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  tier: standard
  #  should use the network of GKE cluster
  network: vpctest1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: partyapvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: partya-volume
  resources:
    requests:
      storage: 1Ti
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: partyb-volume
provisioner: volume.csi.storage.gke.io
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  tier: standard
  #  should use the network of GKE cluster
  network: vpctest1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: partybpvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: partyb-volume
  resources:
    requests:
      storage: 1Ti
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: partyc-volume
provisioner: volume.csi.storage.gke.io
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  tier: standard
  #  should use the network of GKE cluster
  network: vpctest1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: partycpvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: partyc-volume
  resources:
    requests:
      storage: 1Ti
