apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: partyb-filestore
provisioner: filestore.csi.storage.gke.io
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  tier: standard
  #  should use the network of GKE cluster
  network: vpctest1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: partybpvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: partyb-filestore
  resources:
    requests:
      storage: 1Ti
