apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: notary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notary
  template:
    metadata:
      labels:
        app: notary
    spec:
      containers:
        - name: notary
          #          these images should change to your artifact registry
          image: europe-west2-docker.pkg.dev/canvas-hook-339503/corda/corda-os:4.9.6
          env:
            - name: "ROLE"
              value: "NOTARY"
          ports:
            - containerPort: 10002
            - containerPort: 10003
          volumeMounts:
            - name: mypvc
              mountPath: /app
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: notarypvc
---
apiVersion: v1
kind: Service
metadata:
  name: notary
spec:
  type: NodePort
  ports:
    - name: p2p
      port: 10002
      targetPort: 10002
    - name: rpc
      port: 10003
      targetPort: 10003
  selector:
    app: notary
