apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: party-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: party-a
  template:
    metadata:
      labels:
        app: party-a
    spec:
      containers:
        - name: party-a
          #          these images should change to your artifact registry
          image: europe-west2-docker.pkg.dev/canvas-hook-339503/corda/corda-os:4.9.6
          env:
            - name: "ROLE"
              value: "PARTY"
          ports:
            - containerPort: 10002
          volumeMounts:
            - name: mypvc
              mountPath: /app
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: partyapvc
---
apiVersion: v1
kind: Service
metadata:
  name: party-a
  annotations:
    cloud.google.com/l4-rbs: "enabled"
spec:
  type: LoadBalancer
  loadBalancerIP: 35.195.37.166
  externalTrafficPolicy: Cluster
  selector:
    app: party-a
  ports:
    - name: p2p
      protocol: TCP
      port: 10002
      targetPort: 10002
    - name: rpc
      protocol: TCP
      port: 10003
      targetPort: 10003
