apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: party-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: party-c
  template:
    metadata:
      labels:
        app: party-c
    spec:
      containers:
      - name: party-c
          #          these images should change to your artifact registry
        image: europe-west2-docker.pkg.dev/canvas-hook-339503/corda/corda-os:4.9.6
        env:
        - name: "ROLE"
          value: "PARTY"
        ports:
        - containerPort: 10002
        volumeMounts:
          - name: mypvc
            mountPath: /app
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: partycpvc
---
apiVersion: v1
kind: Service
metadata:
  name: party-c
spec:
  type: NodePort
  ports:
    - name: p2p
      port: 10002
      targetPort: 10002
    - name: rpc
      port: 10003
      targetPort: 10003
  selector:
    app: party-c
